# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

#Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.

version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: bankdb
    environment:
      MYSQL_DATABASE: bankdb        # база данных
      MYSQL_USER: dev_user          # пользователь
      MYSQL_PASSWORD: dev_pass      # пароль
      MYSQL_ROOT_PASSWORD: rootpass # root-пароль
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: bank-rest-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bankdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: dev_user
      SPRING_DATASOURCE_PASSWORD: dev_pass
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - db

volumes:
  db_data:

