#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

datasource:
  url: jdbc:mysql://db:3306/bankdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  username: dev_user
  password: dev_pass
  driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  hibernate:
    ddl-auto: validate
  show-sql: true
  properties:
    hibernate.format_sql: true

server:
  port: 8080

token:
  signing:
    key: ${JWT_SECRET}

app:
  card:
    mask-pattern: "**** **** **** %s"

swagger:
  enabled: true

liquibase:
  change-log: classpath:db/migration/changelog-master.xml
  enabled: true

# Настройки Spring Boot Actuator для health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  health:
    defaults:
      enabled: true

